notifications:
  email: false
#Install a Terraform executable locally
before_install:
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64.zip
  - chmod +x deploy_infra.sh

script:
  - ./terraform apply -auto-approve
  - ./deploy_infra.sh
