notifications:
  email: false
#Install a Terraform executable locally
before_install:
  - wget https://releases.hashicorp.com/terraform/0.10.6/terraform_0.10.6_linux_amd64.zip
  - unzip terraform_0.10.6_linux_amd64.zip

script:
  - ./terraform --help init
  - ./deploy_infra.sh
